name: 'Install'
description: 'Sets up Node.js and runs install'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile